export const asset = (name: string) => `/assets/${name}`;

export const images = {
  logo: asset("logo.png"),
  hero: asset("Hero_Image.svg"),
  heroIcon: asset("hero section icon.svg"),
  line2: asset("Line2.svg"),
  episodeOne: asset("Card Image → Episode Image.svg"),
  episodeTwo: asset("Card Image → Episodes Image 2.svg"),
  episodeThree: asset("Card Image → Episodes Image3.svg"),
  episodeFour: asset("Card Image → Episodes Image4.svg"),
  discovery: asset("discovery image.svg"),
  discoveryVector: asset("discovery Vector.svg"),
  discoveryVectorTwo: asset("discovery Vector2.svg"),
  discoveryLine: asset("discovery.svg"),
  podcastPlayerCard: asset("Podcast Player Card.svg"),
  listenGoogle: asset("Link - Default.svg"),
  listenSpotify: asset("Link - Default 2.svg"),
  listenApple: asset("Link - Default 3.png"),
  listenPocket: asset("Link - Default 4.svg"),
  clientOne: asset("Client Image 1.svg"),
  clientTwo: asset("Client Image2.svg"),
  clientThree: asset("Client Image 3.svg"),
  cta: asset("Cta Image.svg"),
  featureBadge: asset("feature - Component 1.png"),
  featurePhoto: asset("feature Image.svg"),
  featureBg: asset("feature_bg.svg"),
  featuresLine: asset("features Line.svg"),
  categoryTech: asset("technology.svg"),
  categoryComedy: asset("comedy.svg"),
  categoryDesign: asset("design.svg"),
  categoryHealth: asset("health.svg"),
  categoryBusiness: asset("business.svg"),
  categoryEducation: asset("education.svg"),
};
